### ISSUE TITLE
mortgage.loan_term is not passing to Velocify

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-velocify#11]
Currently loan.term is string, should it be integer. Value of 30 isn't landing in Velocify at all. 

LCN (MLoA): http://screencast.com/t/FBpmVzlsC
Event URL: https://next.leadconduit.com/events/546ae4071bc8053d5fd8f5cb
Velocify screen grab: http://screencast.com/t/7oCXcRYHi04Z

**Comment by cgrayson** [comment]
If [this](https://docs.google.com/a/activeprospect.com/spreadsheets/d/1ZR5ibg5lN-vgxfBpe6rTKqzubSFF9LWOlVlX_W_IdbM/edit#gid=2068960046) is the master list, then it does show `loan_term_years`, not `loan_term`. 

So that's all that's needed here, right, @alexkwolfe? To change what's sent by the integration? You said "added to our mapping", but I'm not sure what that means.

**Comment by alexkwolfe** [comment]
"Added to our mapping" refers to the mapping that velocify does internally between the parameters we send and their internal fields.

**Comment by ros3bud** [comment]
@kcaponeAP has confirmed that this is currently working as it should.
