### ISSUE TITLE
Question on 'Bankruptcy Was Declared'

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-velocify#24]
I searched the integration, but was not able to find conclusive information about mortgage.application.bankruptcy_was_declared. 

The following lead:
https://next.leadconduit.com/events/54c6d19399cf7a313b7d48b8?event_id=54c6d19499cf7a313b7d48c1

From XXXXXX. A recent lead did not pass bankruptcy_was_declared. I know we've gone over this many times, but wanted to know why this information didn't pass. 

1. Perhaps this is due to the fact that we don't know where we are to route this data in velocify.
2. Perhaps we didn't notice it until this point.

**Comment by zalary** [comment]
Mortgage Application Bankruptcy Was Declared is a boolean field and they are passing the word 'No'  Since that doesn't match true or false, the value gets wiped out when we do the evaluation for what to send to Velocify.

If they can send in true or false as field expects, that should work to pass the value to Velocify in the necessary format.  If they can't change what they pass, a mapping could be created on the inbound for them (if mortgage.bankruptcy_was_declared = No, then set false, if Yes, then true)

**Comment by alexkwolfe** [comment]
This is a bug that will be addressed in the next release. The lead you referenced was submitted with `mortgage.bankruptcy.was_declared=No`. The Velocity integration expects either `true` or `false`. 

After the next release, the value `"No"` will be automatically converted to "true" or "false" when the lead is first submitted.

**Comment by alexkwolfe** [comment]
But yeah. Zalary is right. It can be solved today using a inbound or outbound mapping.

**Comment by kcaponeAP** [comment]
If I map this today, will I have to go back and unmap it once the deployment addresses this?

**Comment by alexkwolfe** [comment]
You won't **have** to. Your mapping won't cause a problem. But it will be extraneous and should be removed because it could cause future confusion.

**Comment by kcaponeAP** [comment]
Understood.
