### ISSUE TITLE
Populate Mortgage Application Credit Rating

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-velocify#25]
We are using the new Lower My Bills integration. Credit Rating did not pass to Velocify. Can you please see that this is added to the integration?

**Comment by kcaponeAP** [comment]
This is for the MLOA account.

**Comment by alexkwolfe** [comment]
This integration does not support the `mortgage.application.credit_rating` field (because it is deprecated). 

The problem is that the LowerMyBills integration is populating a [deprecated field](http://docs.leadconduit.com/fields?q=credit).  

I have opened [a new issue](https://github.com/activeprospect/leadconduit-integration-lowermybills/issues/6) against the appropriate integration.

**Comment by alexkwolfe** [comment]
In the meantime, you can solve this problem with a mapping.

**Comment by kcaponeAP** [comment]
Understood.
