### ISSUE TITLE
Provide more accurate reason when Velocify is in "script upgrade mode"

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-velocify#41]
Over the weekend, we had a response from Velocify that presented us with error. Should the response be failure, as the service was not available at the time of transaction.

https://next.leadconduit.com/events/555847409dfb448203c0e9f3?event_id=555847429dfb448203c0e9fe

```
HTTP/1.1 200 OK
Cache-Control: private
Content-Length: 254
Content-Type: text/xml; charset=utf-8
Date: Sun, 17 May 2015 07:46:11 GMT
Server: Microsoft-IIS/7.5
Set-Cookie: ["ASP.NET_SessionId=rxmb31h2irctfenjo4lpruzo; path=/; HttpOnly"]
X-Aspnet-Version: 4.0.30319
X-Powered-By: ASP.NET
 <?xml version="1.0" encoding="UTF-8"?><ImportResults><ImportResult refId="" leadId="0" result="Failure" message="Login failed for user 'masterDAC'. Reason: Server is in script upgrade mode. Only administrator can connect at this time." /></ImportResults>
```

**Comment by alexkwolfe** [comment]
Nice catch. I think we still want an `error` outcome, but the reason should be something like "Velocify is in maintenance mode".

**Comment by kcaponeAP** [comment]
For posterity so when that lead expires...

<?xml version="1.0" encoding="UTF-8"?><ImportResults><ImportResult refId="" leadId="0" result="Failure" message="Login failed for user 'masterDAC'. Reason: Server is in script upgrade mode. Only administrator can connect at this time." /></ImportResults>

**Comment by cgrayson** [comment]
Similar message to handle, from #39: 

`<?xml version="1.0" encoding="UTF-8"?><ImportResults><ImportResult refId="" leadId="0" result="Failure" message="A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 0 - A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)" /></ImportResults>`
